// PROJECT TYPES
export const LOADING_PROJECT_STARTED = 'LOADING_PROJECT_STARTED'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE'

// CONSTRUCTION ESTIMATE TYPES
export const LOADING_CONSTRUCTION_ESTIMATE_STARTED = 'LOADING_CONSTRUCTION_ESTIMATE_STARTED'
export const CREATE_CONSTRUCTION_ESTIMATE_SUCCESS = 'CREATE_CONSTRUCTION_ESTIMATE_SUCCESS'
export const CREATE_CONSTRUCTION_ESTIMATE_FAILURE = 'CREATE_CONSTRUCTION_ESTIMATE_FAILURE'
export const DELETE_CONSTRUCTION_ESTIMATE_SUCCESS = 'DELETE_CONSTRUCTION_ESTIMATE_SUCCESS'
export const DELETE_CONSTRUCTION_ESTIMATE_FAILURE = 'DELETE_CONSTRUCTION_ESTIMATE_FAILURE'
export const UPDATE_CONSTRUCTION_ESTIMATE_SUCCESS = 'UPDATE_CONSTRUCTION_ESTIMATE_SUCCESS'
export const UPDATE_CONSTRUCTION_ESTIMATE_FAILURE = 'UPDATE_CONSTRUCTION_ESTIMATE_FAILURE'

// PLANS ESTIMATE TYPES
export const LOADING_PLANS_ESTIMATE_STARTED = 'LOADING_PLANS_ESTIMATE_STARTED'
export const CREATE_PLANS_ESTIMATE_SUCCESS = 'CREATE_PLANS_ESTIMATE_SUCCESS'
export const CREATE_PLANS_ESTIMATE_FAILURE = 'CREATE_PLANS_ESTIMATE_FAILURE'
export const DELETE_PLANS_ESTIMATE_SUCCESS = 'DELETE_PLANS_ESTIMATE_SUCCESS'
export const DELETE_PLANS_ESTIMATE_FAILURE = 'DELETE_PLANS_ESTIMATE_FAILURE'
export const UPDATE_PLANS_ESTIMATE_SUCCESS = 'UPDATE_PLANS_ESTIMATE_SUCCESS'
export const UPDATE_PLANS_ESTIMATE_FAILURE = 'UPDATE_PLANS_ESTIMATE_FAILURE'

// PLANS COST TYPES
export const LOADING_PLANS_COST_STARTED = 'LOADING_PLANS_COST_STARTED'
export const CREATE_PLANS_COST_SUCCESS = 'CREATE_PLANS_COST_SUCCESS'
export const CREATE_PLANS_COST_FAILURE = 'CREATE_PLANS_COST_FAILURE'
export const DELETE_PLANS_COST_SUCCESS = 'DELETE_PLANS_COST_SUCCESS'
export const DELETE_PLANS_COST_FAILURE = 'DELETE_PLANS_COST_FAILURE'
export const UPDATE_PLANS_COST_SUCCESS = 'UPDATE_PLANS_COST_SUCCESS'
export const UPDATE_PLANS_COST_FAILURE = 'UPDATE_PLANS_COST_FAILURE'

// SITE TYPES
export const LOADING_SITE_STARTED = 'LOADING_SITE_STARTED'
export const CREATE_SITE_SUCCESS = 'CREATE_SITE_SUCCESS'
export const CREATE_SITE_FAILURE = 'CREATE_SITE_FAILURE'
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS'
export const DELETE_SITE_FAILURE = 'DELETE_SITE_FAILURE'
export const UPDATE_SITE_SUCCESS = 'UPDATE_SITE_SUCCESS'
export const UPDATE_SITE_FAILURE = 'UPDATE_SITE_FAILURE'

// REROOF TYPES
export const LOADING_REROOF_STARTED = 'LOADING_REROOF_STARTED'
export const CREATE_REROOF_SUCCESS = 'CREATE_REROOF_SUCCESS'
export const CREATE_REROOF_FAILURE = 'CREATE_REROOF_FAILURE'
export const DELETE_REROOF_SUCCESS = 'DELETE_REROOF_SUCCESS'
export const DELETE_REROOF_FAILURE = 'DELETE_REROOF_FAILURE'
export const UPDATE_REROOF_SUCCESS = 'UPDATE_REROOF_SUCCESS'
export const UPDATE_REROOF_FAILURE = 'UPDATE_REROOF_FAILURE'

// MECHANICAL TYPES
export const LOADING_MECHANICAL_STARTED = 'LOADING_MECHANICAL_STARTED'
export const CREATE_MECHANICAL_SUCCESS = 'CREATE_MECHANICAL_SUCCESS'
export const CREATE_MECHANICAL_FAILURE = 'CREATE_MECHANICAL_FAILURE'
export const DELETE_MECHANICAL_SUCCESS = 'DELETE_MECHANICAL_SUCCESS'
export const DELETE_MECHANICAL_FAILURE = 'DELETE_MECHANICAL_FAILURE'
export const UPDATE_MECHANICAL_SUCCESS = 'UPDATE_MECHANICAL_SUCCESS'
export const UPDATE_MECHANICAL_FAILURE = 'UPDATE_MECHANICAL_FAILURE'

// ELECTRICAL TYPES
export const LOADING_ELECTRICAL_STARTED = 'LOADING_ELECTRICAL_STARTED'
export const CREATE_ELECTRICAL_SUCCESS = 'CREATE_ELECTRICAL_SUCCESS'
export const CREATE_ELECTRICAL_FAILURE = 'CREATE_ELECTRICAL_FAILURE'
export const DELETE_ELECTRICAL_SUCCESS = 'DELETE_ELECTRICAL_SUCCESS'
export const DELETE_ELECTRICAL_FAILURE = 'DELETE_ELECTRICAL_FAILURE'
export const UPDATE_ELECTRICAL_SUCCESS = 'UPDATE_ELECTRICAL_SUCCESS'
export const UPDATE_ELECTRICAL_FAILURE = 'UPDATE_ELECTRICAL_FAILURE'

// PLUMBING TYPES
export const LOADING_PLUMBING_STARTED = 'LOADING_PLUMBING_STARTED'
export const CREATE_PLUMBING_SUCCESS = 'CREATE_PLUMBING_SUCCESS'
export const CREATE_PLUMBING_FAILURE = 'CREATE_PLUMBING_FAILURE'
export const DELETE_PLUMBING_SUCCESS = 'DELETE_PLUMBING_SUCCESS'
export const DELETE_PLUMBING_FAILURE = 'DELETE_PLUMBING_FAILURE'
export const UPDATE_PLUMBING_SUCCESS = 'UPDATE_PLUMBING_SUCCESS'
export const UPDATE_PLUMBING_FAILURE = 'UPDATE_PLUMBING_FAILURE'

// BUILDING TYPES
export const LOADING_BUILDING_STARTED = 'LOADING_BUILDING_STARTED'
export const CREATE_BUILDING_SUCCESS = 'CREATE_BUILDING_SUCCESS'
export const CREATE_BUILDING_FAILURE = 'CREATE_BUILDING_FAILURE'
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS'
export const DELETE_BUILDING_FAILURE = 'DELETE_BUILDING_FAILURE'
export const UPDATE_BUILDING_SUCCESS = 'UPDATE_BUILDING_SUCCESS'
export const UPDATE_BUILDING_FAILURE = 'UPDATE_BUILDING_FAILURE'

